# RGB
RGBMATRIX_ENABLE = yes
#Mod Keys
MOUSEKEY_ENABLE = yes
MOUSE_ENABLE =  yes
DEFERRED_EXEC_ENABLE = yes
KEYLOCK_ENABLE = yes
EXTRAKEY_ENABLE = yes
CAPS_WORD_ENABLE = yes
VELOCIKEY_ENABLE = yes
SEND_STRING_ENABLE = yes
#MISC
CONSOLE_ENABLE = yes
UNICODE_ENABLE = yes
ENCODER_ENABLE = yes
WPM_ENABLE = yes
#Bootloader
BOOTLOADER = rp2040
CONVERT_TO = promicro_rp2040
